Fix NoClassDefFoundError that occured when java plugins try to find classes that weren't loaded yet. This fix is rather a workaround since it force loads all classes in the scalaplugin.